export const example = `.eslintignore
.eslintrc.yml
.github/workflows/ci.yml
.gitignore
.prettierrc
LICENSE
README.md
package.json
playwright.config.ts
postcss.config.cjs
renovate.json
src/app.html
src/app.postcss
src/hooks.client.ts
src/hooks.server.ts
src/lib/index.ts
src/lib/minify.test.ts
src/lib/minify.ts
src/lib/steps/convert.ts
src/lib/steps/postprocess.ts
src/lib/steps/preprocess.ts
src/lib/types/Collapsed.ts
src/lib/types/Input.ts
src/lib/types/Options.ts
src/lib/types/Output.ts
src/lib/types/TreeNode.ts
src/lib/types/index.ts
src/lib/utils/collapse-flat.test.ts
src/lib/utils/collapse-nest.test.ts
src/lib/utils/collapse-one-line.test.ts
src/lib/utils/collapse.test.ts
src/lib/utils/collapse.ts
src/lib/utils/folding-array.test.ts
src/lib/utils/folding-dict.test.ts
src/lib/utils/folding.test.ts
src/lib/utils/folding.ts
src/lib/utils/make-indented-list.test.ts
src/lib/utils/make-indented-list.ts
src/lib/utils/to-tree.ts
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/Diff.svelte
src/routes/GitHubLogo.svelte
src/routes/Result.svelte
src/routes/Toggle.svelte
src/routes/example.ts
src/routes/large-example.txt
static/apple-touch-icon-precomposed.png
static/apple-touch-icon.png
static/favicon.ico
static/favicon.png
static/favicon.svg
static/fonts/BebasNeue-Regular.ttf
static/og-image.png
svelte.config.js
tailwind.config.ts
tsconfig.json
vite.config.ts`
